# steps:
#   # Step 1: Build and push the container image using Cloud Buildpacks
#   - name: "gcr.io/cloud-builders/gcp-workloads"
#     args: ["builds", "submit", "--pack", "image", "--builder=gcr.io/buildpacks/builder:v1", "--tag=gcr.io/norse-quest-403404/bostondao-telegram-container"]

#   # Step 2: Deploy to Cloud Run
#   - name: "gcr.io/cloud-builders/gcloud"
#     args:
#       - "run"
#       - "deploy"
#       - "bostondao-telegram-container"
#       - "--image"
#       - "gcr.io/norse-quest-403404/bostondao-telegram-container"
#       - "--platform"
#       - "managed"
#       - "--region"
#       - "us-central1"  # Replace with your desired region
#       - "--port"
#       - "8080"
#       - "--allow-unauthenticated"


steps:
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--network=cloudbuild'
      - '--path=.'
    id: Buildpack
    entrypoint: pack
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: bostondao-telegram-bot
  _DEPLOY_REGION: us-central1
  _TRIGGER_ID: 31e39fa7-ca11-4a31-b13a-c6128aa6847a
  _AR_HOSTNAME: us-central1-docker.pkg.dev
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - bostondao-telegram-bot
